### ISSUE TITLE
Support custom shortcut

### ISSUE THREAD

**Issue by csaez** [csaez/quicklauncher#10]
It would be cool to be able to set any key as shortcut by generalizing the mechanism used by the `tab` setup (the `tab key` is reserved by Maya's native shortcut support and `quicklauncher` manage the shortcut through pyside, unfortunately `tab` is heavily used to move the focus between fields in the attribute editor and people might want to set other key).

**Comment by csaez** [comment]
After giving it some thoughts, I think it's better to leave this to the host application, otherwise we will have clashes with existing shortcuts defined by other systems making it very tricky to manage.

Actually, looking back, the tab setup thingy was kind of a bad idea, `quicklauncher` shouldn't override  host application's functionality and I'm tempted to remove it (fortunately it's opt-in).

**Comment by dshlai** [comment]
How about Sublime Text Style command palette shortcut for launching the menu, e.g., [ctrl-shift-p]? It seems to me the combination of left side modifier combine with letters on the right hand keyboard position  better suit for this purpose.

**Comment by csaez** [comment]
Hi @dshlai,
Sure, you can assign whatever you want through Maya hotkey editor (just like anything else), the reason of the TAB shortcut being included here is because Maya doesn't expose that key (kind of a special case), but you can totally go sublime-ish or whatever makes sense to you (I personally use Ctrl+P because that's [what my code editor of choice uses](https://kien.github.io/ctrlp.vim/)... and it works great :) ).

Cheers!
