### ISSUE TITLE
similar apps

### ISSUE THREAD

**Issue by hannesdelbeke** [csaez/quicklauncher#19]
came across some similar apps for Maya

Maya now has a default search bar.
press CTRL F in Maya to bring it up.
it does not appear to support custom commands

Cosmos is a nice 3rd party search bar with more features, 
it does not allow commercial use. 
it accepts custom commands
https://deerstranger.gumroad.com/l/cosmos

**Comment by csaez** [comment]
Yeah, cosmos seems to be the more feature complete (also, the GUI looks very polished).

That said, I don't see how the existence of alternatives are an issue for this project, so I'm going to close this issue in the spirit of keeping these as actionable items leading to improving the project.

Cheers!
